name: DUTTv2
channels:
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - affine=2.4.0=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py311h5547dcb_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.2=pyha770c72_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blosc=1.21.2=hebb52c4_0
  - boost-cpp=1.78.0=h31500c2_2
  - branca=0.6.0=pyhd8ed1ab_0
  - brotli=1.0.9=hb7f2c08_8
  - brotli-bin=1.0.9=hb7f2c08_8
  - brotlipy=0.7.0=py311h5547dcb_1005
  - bzip2=1.0.8=h0d85af4_4
  - c-ares=1.18.1=h0d85af4_0
  - ca-certificates=2022.12.7=h033912b_0
  - cairo=1.16.0=h904041c_1014
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py311ha86e640_3
  - cfitsio=4.2.0=hd56cc12_0
  - charset-normalizer=3.1.0=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - click-plugins=1.1.1=py_0
  - cligj=0.7.2=pyhd8ed1ab_1
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contextily=1.3.0=pyhd8ed1ab_0
  - contourpy=1.0.7=py311hd2070f0_0
  - cryptography=40.0.2=py311h61927ef_0
  - curl=8.0.1=h1fead75_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - debugpy=1.6.7=py311h814d153_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hf0c8a7f_1
  - fiona=1.9.3=py311h9687163_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - folium=0.14.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h5bb23bf_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.39.3=py311h5547dcb_0
  - freetype=2.12.1=h3f81eb7_1
  - freexl=1.0.6=hb7f2c08_1
  - gdal=3.6.3=py311h619941e_1
  - geographiclib=1.52=pyhd8ed1ab_0
  - geopandas=0.12.2=pyhd8ed1ab_0
  - geopandas-base=0.12.2=pyha770c72_0
  - geopy=2.3.0=pyhd8ed1ab_0
  - geos=3.11.2=hf0c8a7f_0
  - geotiff=1.7.1=h6d03f96_7
  - gettext=0.21.1=h8a4c099_0
  - giflib=5.2.1=hb7f2c08_3
  - hdf4=4.2.15=h9804679_6
  - hdf5=1.12.2=nompi_h48135f9_101
  - icu=70.1=h96cf925_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.6.0=pyha770c72_0
  - importlib_metadata=6.6.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.22.0=pyh736e0ef_0
  - ipython=8.12.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.2=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.2.0=pyhd8ed1ab_0
  - json-c=0.16=h01d06f9_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py311h6eed73b_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.5.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - kealib=1.5.0=h5c1f988_0
  - kiwisolver=1.4.4=py311hd2070f0_1
  - krb5=1.20.1=h049b76e_0
  - lcms2=2.15=h2dcdeff_1
  - lerc=4.0.0=hb486fe8_0
  - libaec=1.0.6=hf0c8a7f_1
  - libblas=3.9.0=16_osx64_openblas
  - libbrotlicommon=1.0.9=hb7f2c08_8
  - libbrotlidec=1.0.9=hb7f2c08_8
  - libbrotlienc=1.0.9=hb7f2c08_8
  - libcblas=3.9.0=16_osx64_openblas
  - libcurl=8.0.1=h1fead75_0
  - libcxx=16.0.2=hd57cbcb_0
  - libdeflate=1.17=hac1461d_0
  - libedit=3.1.20191231=h0678c8f_2
  - libev=4.33=haf1e3a3_1
  - libexpat=2.5.0=hf0c8a7f_1
  - libffi=3.4.2=h0d85af4_5
  - libgdal=3.6.3=h8ea55aa_1
  - libgfortran=5.0.0=11_3_0_h97931a8_31
  - libgfortran5=12.2.0=he409387_31
  - libglib=2.76.2=hc62aa5d_0
  - libiconv=1.17=hac89ed1_0
  - libjpeg-turbo=2.1.5.1=hb7f2c08_0
  - libkml=1.3.0=haeb80ef_1015
  - liblapack=3.9.0=16_osx64_openblas
  - libnetcdf=4.9.1=nompi_hb17d2b5_102
  - libnghttp2=1.52.0=he2ab024_0
  - libopenblas=0.3.21=openmp_h429af6e_3
  - libpng=1.6.39=ha978bb4_0
  - libpq=15.2=h3640bf0_0
  - librttopo=1.1.0=h5c328d2_13
  - libsodium=1.0.18=hbcb3906_1
  - libspatialindex=1.9.3=he49afe7_4
  - libspatialite=5.0.1=h595bb97_24
  - libsqlite=3.40.0=ha978bb4_1
  - libssh2=1.10.0=h47af595_3
  - libtiff=4.5.0=hd920806_5
  - libwebp-base=1.3.0=hb7f2c08_0
  - libxcb=1.13=h0d85af4_1004
  - libxml2=2.10.3=h201ad9d_4
  - libzip=1.9.2=h6db710c_1
  - libzlib=1.2.13=hfd90126_4
  - llvm-openmp=16.0.2=hff08bdf_0
  - lz4-c=1.9.4=hf0c8a7f_0
  - mapclassify=2.5.0=pyhd8ed1ab_1
  - markupsafe=2.1.2=py311h5547dcb_0
  - matplotlib-base=3.7.1=py311h2bf763f_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mercantile=1.2.1=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - munch=2.5.0=py_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - nb_conda_kernels=2.3.1=py311h6eed73b_2
  - nbclassic=0.5.5=pyh8b2e9e2_0
  - nbclient=0.7.3=pyhd8ed1ab_0
  - nbconvert-core=7.3.1=pyhd8ed1ab_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - ncurses=6.3=h96cf925_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - notebook=6.5.4=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - nspr=4.35=hea0b92c_0
  - nss=3.89=h78b00b3_0
  - numpy=1.24.3=py311hc44ba51_0
  - openjpeg=2.5.0=h13ac156_2
  - openssl=3.1.0=h8a1eda9_1
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.1=py311hab14417_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre2=10.40=h1c4e4bc_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.5.0=py311hf47c0a6_0
  - pip=23.1.1=pyhd8ed1ab_0
  - pixman=0.40.0=hbcb3906_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - pooch=1.7.0=pyha770c72_3
  - poppler=23.03.0=hc777cac_1
  - poppler-data=0.4.12=hd8ed1ab_0
  - postgresql=15.2=hbea33b9_0
  - proj=9.1.1=hf909084_2
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.5=py311h5547dcb_0
  - pthread-stubs=0.4=hc929b4f_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.15.1=pyhd8ed1ab_0
  - pyopenssl=23.1.1=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyproj=3.5.0=py311hdc3c720_0
  - pyrsistent=0.19.3=py311h5547dcb_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.11.3=h99528f9_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.11=3_cp311
  - pytz=2023.3=pyhd8ed1ab_0
  - pyyaml=6.0=py311h5547dcb_5
  - pyzmq=25.0.2=py311habfacb3_0
  - rasterio=1.3.6=py311hc41c901_0
  - readline=8.2=h9e318b2_1
  - requests=2.28.2=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rtree=1.0.1=py311hbc1f44b_1
  - scikit-learn=1.2.2=py311hda7f639_1
  - scipy=1.10.1=py311h939689b_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=67.7.1=pyhd8ed1ab_0
  - shapely=2.0.1=py311heb7bb94_1
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h225ccf5_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - snuggs=1.4.7=py_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.40.0=h9ae0607_1
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tiledb=2.13.2=h8b9cbf0_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=h5dbffcc_0
  - tornado=6.3=py311h5547dcb_0
  - tqdm=4.65.0=pyhd8ed1ab_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzcode=2023c=hb7f2c08_0
  - tzdata=2023c=h71feb2d_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xerces-c=3.2.4=h2007e90_1
  - xorg-libxau=1.0.9=h35c211d_0
  - xorg-libxdmcp=1.1.3=h35c211d_0
  - xyzservices=2023.2.0=pyhd8ed1ab_0
  - xz=5.2.6=h775f41a_0
  - yaml=0.2.5=h0d85af4_2
  - zeromq=4.3.4=he49afe7_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=hfd90126_4
  - zstd=1.5.2=hbc0c0cd_6
prefix: /Users/ivo/opt/anaconda3/envs/DUTTv2
